### PR TITLE
Updated the link to the FoFIX website

### PR DESCRIPTION
**Pull request by Baklap4**
Linked from: https://github.com/performous/web/pull/7

Patched the files to work for `gh-pages` branch as that's the live code for the website.

Closes #7

### CODE REVIEW

**Review by Linkid — COMMENTED** [review]
Hi! Thank you for this change.
Now, the website is https://fofix.org ;).

**Comment by Baklap4** [comment]
@Linkid i'll fix that right away ;)

**Review by Tronic — CHANGES_REQUESTED** [review]
Please don't edit the generated HTML but rather the TXT source files and then run webconv to regenerate the HTML.

https://github.com/performous/web/blob/master/htdocs-source/blog.txt
https://github.com/performous/web/blob/master/htdocs-source/others.txt
https://github.com/performous/web/tree/master/webconv

You may be able to use the deploy scripts, possibly with modifications, to generate and upload.

**Comment by Baklap4** [comment]
> Please don't edit the generated HTML but rather the TXT source files and then run webconv to regenerate the HTML.

@Tronic i think you can provide some info over at #9  If it is the case that the html is generated based on that source then ghpages should reflect that which it doesn't.  So there's 2 options 1) run the webconv to regen the html (possibly within ci) or scratch the whole webconv and 2) just have a static page at the current gh-pages branches. Anyway more info about that is in the beforementioned issue.

**Comment by Tronic** [comment]
Maintaining the navigation menu by hand is cumbersome if editing static HTML because the menu needs to be correctly duplicated on each file. So I think the options are either one of:

- Check git log of the last few years for any changes done to HTML files, and backport them to TXT, then re-run webconv and keep using it.
- Install some modern CMS (maybe one that generates static HTML but provides editing in browser) and remake the whole site using themes and everything from the CMS.

Editing those static HTML files combines the worst of both worlds, and thus should be avoided at all cost.

**Pull request closed without merging**
