### PR TITLE
Update the link to the FoFiX website

### PR DESCRIPTION
**Pull request by Linkid**
Google Code is not used anymore by FoFiX.

### CODE REVIEW

**Comment by Tronic** [comment]
Cool, and nice to see that they're still alive :)

Now I only wonder whether anyone in Performous team still knows to update the website from these sources. The last update is apparently from 2016, probably by me.

**Comment by Baklap4** [comment]
@Tronic i've never know how.. so feel free to enlighten us, how is the site even hosted?

**Comment by Tronic** [comment]
It is static HTML, converted by https://github.com/performous/web/tree/master/webconv

The site is probably hosted by Yoda since 2016, so you'd have to try and reach him to be able to upload the new files to performous.org.

**Comment by Tronic** [comment]
The **webconv** format is my design from early 2000's, before either MarkDown or reStructuredText became popular, and webconv also handles website navigation, much alike you can with .rst nowadays. Like the docs say, webconv was never officially released, and AFAIK is not used by anyone else than Performous anymore.

Needless to say, the site and this technology are badly outdated, and if anyone has the energy, I'd suggest a modern replacement from scratch. Fortunately it looks like static site generation is gaining newfound popularity, because the stupidest thing ever would be to run PHP or React apps to serve entirely static content.

The background video autoplay doesn't work with new browsers and the scrolling screenshots could be made smooth with CSS animations (back at the day I had to do it in Javascript). And the content, well... Needs to be updated.

**Comment by Lord-Kamina** [comment]
Who owns the domain, @yoda-jm ?
Would github pages be an option or is it too basic?

**Comment by yoda-jm** [comment]
> Who owns the domain, @yoda-jm ?
> Would github pages be an option or is it too basic?

Yes, I am the owner of the domain.
We could completely go for a static web-page hosted on GitHub, we need to write a few html but this is no problem. I already host a few website on GitHub so I know how to configure it.

**Comment by Baklap4** [comment]
Closing this PR since the changed are cloned to #10  as the current master branch is not the source what's being presented live. That's on the gh-pages branch.

What to do with the master branch? Please discuss in #9

**Comment by Baklap4** [comment]
@Linkid Please see -> #14 . This can be merged when #13 is merged

**Pull request closed without merging**
